In [1]:
import numpy as np

In [6]:
a = 34

In [4]:
a = 50

In [7]:
a

34

In [8]:
type(a)

int

In [9]:
b = 70.33

In [10]:
type(b)

float

In [11]:
c = 'Aditya'

In [12]:
type(c)

str

#### ceating an array

In [18]:
arr = np.array([12,23,34,45,56])

In [19]:
print(arr)

[12 23 34 45 56]


In [20]:
arr

array([12, 23, 34, 45, 56])

In [21]:
type(arr)

numpy.ndarray

In [23]:
arr.ndim # shows the dimension

1

In [25]:
arr1 = np.array([23,45,56,1.2])

In [26]:
arr1

array([23. , 45. , 56. ,  1.2])

In [27]:
arr1 = np.array([23,45,56,1.2, 'Aditya'])

In [28]:
arr1

array(['23', '45', '56', '1.2', 'Aditya'], dtype='<U32')

In [31]:
arr1.dtype

dtype('<U32')

#### indexing/ slicing

In [29]:
arr

array([12, 23, 34, 45, 56])

In [30]:
arr[1]

23

In [32]:
arr + 10

array([22, 33, 44, 55, 66])

In [34]:
arr = arr + 12 * 1.2

In [35]:
arr

array([26.4, 37.4, 48.4, 59.4, 70.4])

In [36]:
arr1 = np.arange(10)

In [37]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(3, 12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
np.arange(-3, 12)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr1[2:6]

array([2, 3, 4, 5])

In [45]:
arr1[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [47]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [50]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr.shape

(4, 3)

In [53]:
arr.size

12

In [52]:
arr.ndim

2

In [54]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [56]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [57]:
arr.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [58]:
arr.reshape(-1, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [59]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [61]:
arr.reshape(3,2,2).ndim

3

In [62]:
arr.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [63]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [65]:
arr[1:,:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
arr[2,1]

8

In [67]:
z = np.array([34,45,65,34,21,34])

In [68]:
np.unique(z)

array([21, 34, 45, 65])

In [69]:
np.mean(z)

38.833333333333336

In [70]:
np.median(z)

34.0

In [77]:
import statistics as s

In [78]:
s.mode(z)

34

In [82]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
np.linalg.matrix_rank(arr)

2

In [86]:
np.linalg.det(arr)

-9.51619735392994e-16

In [87]:
np.linalg.inv(arr)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [88]:
arr.T  # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])